### ISSUE TITLE
Invalid file referrence

### ISSUE THREAD

**Issue by MortezaT** [behnood-eghbali/python-singleton#1]
I think you should use relative path [here](https://github.com/behnood-eghbali/python-singleton/blob/58a9e75ea0dfbd89513528e4cf9c74b95a190b71/bin/singleton/logger.py#L3) otherwise Any one who gonna run it must place `data.log` in the exact path mentioned.

**Comment by behnood-eghbali** [comment]
@MortezaT Thank you for your attention. You're absolutely right.
