### ISSUE TITLE
OOP

### ISSUE THREAD

**Issue by behnood-eghbali** [behnood-eghbali/python-singleton#2]
Implement a logger class:
Keep the benefits of object-oriented programming while taking control of the object-creation process out of the hands of the programmer using the logger. Take control of the process by which the logger object is created. Use the class to verify that the singleton implementation does what you would expect it to do.

**Comment by Priyansh2001here** [comment]
can you please elaborate more on this

**Comment by behnood-eghbali** [comment]
@Priyansh2001here In the log file, we want each message to be prepended with the level associated with the message. This helps us easily scan the file for specific types of messages. Also, we have a loop where we tell Python to write a message log message _i_ every time the loop runs, where _i_ is the index of the loop in the range. The logger handles these levels: 
**• Critical
• Error
• Warning
• Info
• Debug**
We use a logger function to write log messages to the file system in our `main.py` file.
